version: '3'

services:
  app:
    build: ./docker/node
    container_name: 'app'
    restart: always
    volumes:
      - ./:/var/www/app
    ports:
      - 9000:9000
    command:
      sh -c 'npm i && node server.js'

  postgres:
    image: postgres:14.3-alpine
    container_name: 'postgres'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./src/db/database.sql:/database.sql

  # Interactive interface to access postgres database
  # https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: 'pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tripper.com
      - PGADMIN_DEFAULT_PASSWORD=tripper@123
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local